### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by kingboydev** [Verre2OuiSki/CapesLocker#3]
Add mysql support

**Comment by Unarray** [comment]
Hello !
It's been a while now that I'm hesitating to completely redo the plugin because I created it when I first started programming so a lot of things inside are poorly thought out, optimized, structured, etc...

If I decide to redo it, there's a lot of work involved in making something clean, complete and optimized.
As I'm starting from a bad design, the way the data is stored will also change. This change will break all servers using this plugin with the current version. So if I want to redo this plugin, that means I'll have to make an additional tool so that people can convert their current data to the new data structure. 

Otherwise, yes, if I do it again, I'll add MySQL support! But for now, I'll just fix the reported bugs. I don't want to add new features on the current state of the project...

**Comment by Unarray** [comment]
Maybe I'll do this big refactor during pocketmine version 5, who knows?
